name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - '25.3'
          - '26.1'
          - '26.2'
          - '26.3'
        node-version:
          - '10'
          - '12'
          - '13'
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set environement variables
        run: |
          echo "::add-path::$HOME/.cask/bin"

      - name: Install dependencies
        run: |
          curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
          cask

      - name: Run tests
        run: |
          node -v
          make test
