language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/senny/8003271/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.4-bin
script:
  - emacs --version
  - make test
